version: '3.7'

services:
  pz2021-mysql:
    container_name: pz2021-mysql-stage
    ports:
      - '33062:3306'

  pz2021-php:
    container_name: pz2021-php-stage
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@pz2021-mysql:3306/pz2021_stage

  pz2021-nginx:
    container_name: pz2021-nginx-stage
    ports:
      - '8082:80'
