version: '3.7'

services:
  pz2021-mysql:
    container_name: pz2021-mysql-prod
    ports:
      - '33061:3306'
  pz2021-php:
    container_name: pz2021-php-prod
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@pz2021-mysql:3306/pz2021_prod

  pz2021-nginx:
    container_name: pz2021-nginx-prod
    ports:
      - '8081:80'
